lndk-org/lndk

Cargo.toml, src/main.rs
This PR implements the portions of the `NodeSigner` trait that are required for onion messages. Methods that are not required are just left as `unimplemented` because we do not expect the onion messages code to call them.
Fixes #4.
=> Implement NodeSigner trait for LND Node

.github/workflows/main.yml
Resolves #12 
I'm new to rust, so please let me know if any of the steps can be improved (seems like it takes a while, although I understand a lot of dependencies are pulled in).
Also note that uploading to Codecov.io requires initial setup, which involves granting it permissions to your Github repo. If you prefer to upload the results elsewhere, or if there's a CLI step that could display them directly in the output, I'll be glad to update that step.
=> add github CI workflow w/code coverage

.github/workflows/main.yml
Codecov sometimes runs into rate limiting issues from github, including the token directly should help. 
As in: https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
=> actions: include token in codecov action

src/main.rs
A few trivial changes/cleanups:
* Logging fixups (typo + capitalization)
* Remove unnecessary clone of `info`
* Remove panic on bad args and return error instead
=> trivial: Remove args panic and typo fixups

src/main.rs
Channel buffers must be at least one, if LND has no peers when we start up we'd panic.
=> main: buffer by peers length +1 to prevent panic when we have no peers

src/main.rs
Some noisey clippy warnings were introduced in #23, allow `uninlined_format_args` to silence warnings from dependency.
CI didn't trigger this because we allow warnings.
=> Silence clippy warnings from configureme dependency

.github/workflows/audit.yml, CONTRIBUTING.md, README.md
Encourage the use of `cargo-crev` for auditing dependencies. Crev uses a web of trust of entities contributing reviews of crates within the Rust ecosystem in this case. Read more at https://github.com/crev-dev/cargo-crev and see similar use for `rust-bitcoin` at https://github.com/rust-bitcoin/rust-bitcoin/pull/1098.
This commit also adds a GitHub Action for PRs which runs `cargo-audit` to check dependencies for any known vulnerabilities along with their severity and steps to remedy. This should be less noisy than dependabot PRs but we can maybe consider that if we feel it's also helpful to keep track of dependency updates.
Work is part of #38.
=> Add crev note and security audit GH Action for PRs

ARCH.md, README.md
This PR aims to satisfy the first and second release cleanup tasks described in #44:
- Adds instructions for building the specific branch of LND requires, as well as setting the needed protocol flags
- Clarifies some setup instructions by splitting "setting up LNDK" section into a few subsections
- Moves the architecture section of the README into a new file
- Splits the cargo-crev note into a new section of the README
=> README: Release cleanup part 1

.gitignore, README.md, sample-lndk.conf
Updates the "running lndk" instructions to make it more clear there's a configuration option as outlined in #44 . Also thought I'd add a simple sample lndk.conf file and added lndk.conf to the .gitignore.
=> README: Update "running lndk" instructions 

README.md
Just a little PR to make note of where people can ask us questions about lndk. However, I was reading about how discord invite links are impermanent unless you have a particular type of discord server, so emailing us directly might be the best route for discord invites? Thoughts?
If anyone else wants to add their email to the list lmk. Otherwise I'm happy to be the invitation handler.
=> README: Add discord invitation

README.md
A couple tricky little typos that had me confused today heh
=> Fix README make instruction typos

.github/workflows/main.yml, .gitmodules, CONTRIBUTING.md, Cargo.lock, Cargo.toml, Makefile, tests/common/mod.rs, tests/common/test_utils.rs, tests/integration_tests.rs
=> integration tests: setup LND

.gitignore, Cargo.lock, Cargo.toml, config_spec.toml, src/lib.rs, src/lnd.rs, src/main.rs, tests/common/mod.rs, tests/integration_tests.rs
This PR:
- Puts the lndk portion of our integration tests into place, showing that lndk is able to properly forwards onion messages.
- In order to allow us to save lndk's logs to a file for the integration tests, we also swap simple logger with log4rs.
=> integration tests: test that lndk forwards onion message

Cargo.lock, Cargo.toml, README.md, src/cli.rs, src/lib.rs, src/lnd.rs, src/lndk_offers.rs, src/onion_messenger.rs
This PR puts a few things into place as we start to build out functionality to pay an offer: https://github.com/lndk-org/lndk/issues/64
-  Adds the beginnings of a cli binary that users will eventually be able to use to pay an offer. With this, the new cli binary can be run with `cargo run --bin=lndk-cli`. The cli uses clap for parsing arguments.
- Adds functionality to decode an offer and build and sign an invoice request.
Note that the `invoice_request` signing portion needs the following PRs:
https://github.com/lightningnetwork/lnd/pull/8106
https://github.com/lightningdevkit/rust-lightning/pull/2687
https://github.com/orbitalturtle/tonic_lnd/pull/1
More to come!
=> Invoice request

src/lib.rs
This fixes a problem we were having in the integration tests. When we would run the lndk binary in each test -- the second time the logger was initialized it would throw an error. 
With this fix, when the logger is called a second time, it operates normally. Fixes #83.
=> Init logger in a thread-safe manner

README.md
We no longer need a custom branch + explain why we need dev mode.
=> readme: update branch instructions

src/lib.rs, src/lnd.rs, src/lndk_offers.rs
Verify the returned BOLT 12 invoice. Depends on #87
=> Offers: invoice verification

.github/workflows/main.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/lnd.rs, src/lndk_offers.rs, src/onion_messenger.rs, tests/common/mod.rs, tests/integration_tests.rs
Finishes the BOLT 12 offer flow by sending the payment. Depends on #89
=> Offers: send payment 

config_spec.toml, src/cli.rs, src/lib.rs, src/main.rs, tests/integration_tests.rs
While debugging, I ran into a couple of logging things that could be improved a bit.
=> Logging fixes

src/lib.rs, src/lnd.rs, src/lndk_offers.rs
Sets the ppm_fee parameter when querying for a route. My bad for not setting this originally. If not set, this can lead to an offer payment error, because the full fee isn't taken into account.
=> Add missing fee ppm parameter

Cargo.toml, README.md, docs/cli_commands.md, docs/test_pay_offer.md, src/cli.rs, src/lib.rs, src/lnd.rs, src/lndk_offers.rs
This PR adds CLI command `lndk-cli pay-offer`, and adds some documentation for doing so. Depends on #90 
<s>Probably the main change I need to make is to move the reply path code to #87, it makes more sense there!</s>
=> Cli: add pay offer command

.github/workflows/main.yml, src/main.rs
This PR does a couple of things to fix our github actions/CI process:
- Pins the Rust version in Github Actions, because otherwise we get unexpected, new clippy errors when Rust stable has been upgraded to a newer version. Note that this means we'll need to manually upgrade the Rust version in github actions from now on.
- Fixes an attribute problem that clippy didn't like.
=> actions: pin Rust version

Cargo.lock, Cargo.toml, README.md, build.rs, config_spec.toml, docs/cli_commands.md, proto/lndkrpc.proto, src/cli.rs, src/lib.rs, src/lnd.rs, src/lndk_offers.rs, src/main.rs, src/onion_messenger.rs, src/server.rs, tests/integration_tests.rs
This PR sets up a grpc server for interacting with a running LNDK instance. The main command it supports right now is to pay an offer. 
In summary:
- The first few commits are preparatory to pave the way for the grpc server. 
- To interact with LND we need the user to pass in their LND macaroon. We use grpc metadata for this to make it easy to tag this on to each API call.
- Updates the CLI to connect to the server.
=> Setup grpc server

.github/workflows/main.yml, .gitignore, CONTRIBUTING.md, src/cli.rs, src/lib.rs, src/lnd.rs, src/lndk_offers.rs, src/onion_messenger.rs, src/rate_limit.rs, tests/common/mod.rs, tests/common/test_utils.rs, tests/integration_tests.rs
Throughout lndk the comment lengths are all over the place. This PR establishes a standard comment length maximum of 100, which is the same max line length as the rest of the code. The PR also updates the github workflows to enforce this new standard.
Contributors now will need to run `cargo fmt -- --config unstable_features=true --config wrap_comments=true --config comment_width=100` to make sure comments meet this restriction.
We also sneak in a couple other fixes in this PR:
- Update codecov-actions to v4 to fix #114
- Add .vscode to .gitignore
=> Cleanup: cargo fmt max comment length

src/lib.rs, src/onion_messenger.rs
This PR implements solution to #28:
- Adds a sublogger (or subsystem logger) LDK
- Then target that sublogger on MessageInstance
I tried adding just the prefix `ldk: {}` but it didn't feel right.
**Few examples**
Current log
`2024-06-10T19:02:45.197452-04:00 TRACE lndk::onion_messenger - Missing reply path when responding to Offers onion message with path_id None`
Only prefix:
`2024-06-10T19:02:45.197452-04:00 TRACE lndk::onion_messenger - ldk: Missing reply path when responding to Offers onion message with path_id None`
With subsystem (this PR)
`2024-06-10T19:20:58.794410-04:00 TRACE ldk - Missing reply path when responding to Offers onion message with path_id None`
=> logs: add ldk sublogger

Cargo.lock, Cargo.toml, config_spec.toml, docs/cli_commands.md, src/cli.rs, src/lib.rs, src/main.rs, src/server.rs
In a nutshell this PR:
- Requires TLS to be used when connecting to the gRPC server, and generates self-signed certificates for doing so.
- Updates `lndk-cli` to meet this requirement.
- Updates the documentation.
Note that the cert generation portion takes a little inspiration from TEOS and CLN. Credit where it's due!
=> secure the gRPC server with TLS

src/lib.rs, src/lndk_offers.rs, src/server.rs, tests/common/mod.rs, tests/integration_tests.rs
Instead of tracking the offers we're paying, we move to instead track active payments by PaymentId through their lifecycle. This model is more intuitive. It makes it easier for us to track whether we've already received an invoice for the payment or not. As a byproduct, this change also allows us to pay the same offer multiple at once, which we didn't allow for before.
This change also includes some integration test refactoring so we can reuse certain functionality (establishing channels in a network and setting up lndk) across tests.
=> offers: track active payments instead of offers

src/lib.rs, src/lndk_offers.rs
This PR improves debugging logs by:
- Logging when we receive an unverified invoice
- Logging the introduction node in two instances: 1) The introduction node we pick in our invoice request reply path. 2) The introduction node provided in an invoice we are about to pay.
=> offers: improve offer flow logs

Cargo.lock, Cargo.toml, src/lib.rs, src/lnd.rs, src/lndk_offers.rs, src/onion_messenger.rs, src/server.rs, tests/integration_tests.rs
should resolve #118 
Among the changes from previous LDK version:
1. No need to pass `Secp256k1Error` to `SignError`
2. `OnionMessenger` takes extra argument which should implement `NL` referring to `NodeIdLookUp` trait. This required adding new struct `LndkNodeIdLookUp` to implement the above trait.
3. `path.introduction_node` is replaced in favor of `path.introduction_node()`
4. `OfferBuilder` signature change. `OfferBuilder::new` takes now pubkey  instead of disc.
5.  Replace `sign_closure` with `LndkSigner` struct and implemented `SignInvoiceRequestFn` trait for it
Edit: sorry @orbitalturtle I just noticed you assigned yourself to #118!
=> Upgrade to LDK 0.0.123

README.md
This PR updates the LNDK startup instructions to note two things:
- LND v0.18.0 is required.
- The dev flag is no longer required.
=> docs: update startup instructions

Cargo.toml, README.md, config_spec.toml, src/lib.rs, src/lnd.rs, src/main.rs, tests/common/mod.rs, tests/integration_tests.rs
This PR resolves #30 
Check version and build tags of connecting LND at the start of LNDK.
We could make the `has_version` function smaller, but I chose clarity over shotness.
The `has_version` and `has_tags` functions have an optional `requirement` argument, so we can test these functions with constants dedicated to the unit testing.
I have found that LND does not strictly follow semantic versioning. 
LND always release with `beta` pre-release version. Release candidate versions are tagged with something like `beta.rc1`.  If I understand correctly, `0.18.0-beta` < `0.18.0-beta.rc` right?
=> Check LND has required version and build tags on start LNDK.

src/onion_messenger.rs
This PR tackles an issue that has popped up in bolt12-playground when paying Eclair offers.
If we need to connect directly to the introduction node, LNDK's onion messenger receives a PeerConnected event to process this new connection. When we first look at that new peer, the features map is empty, and LNDK decides onion support must be "false". This messes up future payment attempts, because the onion messenger thinks that this peer doesn't support onion messaging, and shouldn't be considered in future payment paths. To fix this, the first commit adds a little wait loop that looks for a non-empty map.
=> Fix peer connect race

src/lndk_offers.rs
Fixes #137 and other related possible panics by removing all of the other unnecessary unwraps when building an invoice request.
=> offers: handle invoice request build failures more gracefully

docs/cli_commands.md, proto/lndkrpc.proto, src/cli.rs, src/lib.rs, src/lndk_offers.rs, src/server.rs
This replaces #129. Thanks to @mauricepoirrier and @mrfelton for doing a lot of the work here.
This PR puts into place a few features requested by @mrfelton/Strike. It does the following:
- Does some refactoring to make way for some new endpoints.
- Adds the `get-invoice` and `pay-invoice` endpoints in described in #124 to give users more control over making offer payments.
- Adds a `decode-invoice` endpoint that takes in a hex-encoded invoice.
- Note that `get-invoice`'s response returns the invoice in two forms: 1) in hex-encoded format 2) decoded into all its pieces as a Bolt12InvoiceContents proto.
=> server: get_invoice and pay_offer endpoints

.github/workflows/audit.yml, .github/workflows/main.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml
* All actions-rs actions are unmaintained, so we'll use dtolnay's rust-toolchain action and just manually run the `cargo` action commands as well as `cargo audit`.
* I've also regenerated release-related workflow with cargo-dist v0.18.0
This should get rid of a bunch of warnings in the actions logs related to node 16 as well, I believe.
=> Update CI actions and replace unmaintained actions

config_spec.toml, docs/cli_commands.md, proto/lndkrpc.proto, src/cli.rs, src/lib.rs, src/lndk_offers.rs, src/main.rs, src/server.rs, tests/integration_tests.rs
This PR includes a few smaller requested changes in one PR:
- Right now the SAN in the tls certificate we autogenerate is hardcoded as localhost. We add a `tls-ip` config option for specifying other ip addresses/domains. Multiple can be added if separated by commas.
- We allow a user to add a "payer note" with either the `pay-offer` and `get-invoice` commands.
- Adds cli documentation for baking a custom macaroon that can be used for paying an offer. 
Closes #134.
=> odds and ends: tls SAN cfg and payer note option

src/server.rs
There is probably a better way to do this, but this does resolve the issue and ensures that the feature bits returned when fetching/decoding an invoice correctly match those set in the invoice.
--- 
This pull request primarily focuses on refactoring the feature conversion logic in the `src/server.rs` file of the project. The changes include the addition of new imports, modifying function parameters, and replacing previous feature conversion logic with new, more specific conversion functions. 
Here are the key changes:
1. New imports added:
* [`src/server.rs`](diffhunk://#diff-48d27698cc708c7efe770fd897e4885efaa0a15cae30d54936068603ba03bbd9R10): Imported `BlindedHopFeatures` and `Bolt12InvoiceFeatures` from the `lightning::ln::features` module. This change suggests that these types will be …
=> server: correctly convert invoice features

src/lnd.rs, src/lndk_offers.rs, tests/integration_tests.rs
We should use a new key to sign each invoice request to improve sender privacy. Closes #116
=> transient keys for signing invoice requests

Cargo.lock, Cargo.toml, src/main.rs
This PR fixes #150 with the following:
- Uses tokio's `signal` feature to process SIGTERM and SIGINT signals, tying them to the `triggered` LifecycleSignals we had in place already.
- Also uses the `serve_with_shutdown` tonic so the server shuts down more gracefully. Maybe it'd be worth looking to see if we can do more for a graceful shutdown later on. With this change, the server seems to work normally. But I'm realizing we don't have any quick integration tests of the server in place. This doesn't necessarily need to go in this PR... but if I have time I'll add something quick.
=> main: handle termination signals

src/lnd.rs, src/lndk_offers.rs, tests/common/mod.rs, tests/integration_tests.rs
When requesting an invoice from an offer, we need to create a reply path for the offer node to reply to. When creating this path we currently don't check whether the introduction node we selected is advertised (with public channels) or not: https://github.com/lndk-org/lndk/blob/259de8b8ef0916393a47d96076db518cf94651f9/src/lndk_offers.rs#L254 
This PR makes sure we pick an advertised node, which the offer node will actually be able to reach, potentially improving payment reliability.
=> offers: don't include unadvertised nodes as introduction node candidates

CHANGELOG.md, Cargo.lock, Cargo.toml
This PR releases LNDK version 0.2.0 using the instructions [here](https://github.com/lndk-org/lndk/blob/master/MAINTAINERS.md). Thanks to @dunxen for setting up this release process.
=> chore: Release lndk version 0.2.0

Cargo.toml
=> chore: use correct protoc version for linux on release

Cargo.toml
Give us what we can even use and we'll pin the protobuf-compiler dependency after the release build.
=> chore: use any linux version for protoc on release

Cargo.toml
LNDK builds are (have been) broken on windows. Disabling release for windows for now.
=> chore: disable windows release support for now

README.md
In the README, example variable names for `lndk.conf` were incorrect. They need to be snake_case rather than kebab-case.
Specifically:
`cert-path` --> `cert_path`
`macaroon-path` --> `macaroon_path`
This commit updates the README with the proper variable names.
Additionally, this commit changes the wording for clarity by specifying LNDK "features" rather than "options".
=> chore: update variable names & provide clarity on features in readme

Cargo.toml, src/rate_limit.rs
This closes #56, but with not the way the issue suggested.
Use `tokio::time::advance` instead of manually updating `rate_limiter.last_update`.
I removed a mock because I don't see any necessity of it, but maybe overlooked something.
=> Use tokio's testing feature to advance time of rate limitter

config_spec.toml, src/lib.rs, src/main.rs, tests/common/mod.rs, tests/integration_tests.rs
In certain deployment scenarios, we may not want (or be able) to write to the default ~/.lndk data directory. For example, the home directory may be mounted as read-only, or mounted using ephemeral storage.
This change adds a new `data_dir` configuration option to specify where LNDK should store data. If this option isn't specified, then falls back to the default ~/.lndk.
=> Added data_dir configuration options.

config_spec.toml, src/lib.rs, src/main.rs
Should close #183
Similar to bitcoin `~/.bitcoin/bitcoin.conf` and `~/.lnd/lnd.conf`, we add ~./lndk as default path to store conf file. 
Added some prevalence root project conf.file wouldn't be overriden by lndk dir conf file.
We move the datadir to defaults to `~/.lndk/data`. If `~/.lndk` does not exists, it tries to create it.
We don't store it inside networks _yet_ as LNDK does not have a concept of network in server, but it does using cli
Add some files with different configurations:
- `lndk.conf` in root project
- `~/.lndk/lndk.conf`
Test which configurations are used. Easy way to do it is to point to different lnd servers and point `address` in each file to each of them.
_Standardness_ and ease when deploying
=> Server: Config defaults to root and Datadir

Dockerfile, sample-docker-compose.yaml
=> Add dockerfile and sample docker compose

src/cli.rs, src/lib.rs
Fixes a couple of bugs introduced in #193:
- The cli was not working because it was trying to find certs in ~/data rather than ~/.lndk/data. Closes #197.
- Logs were be logged in ~/data rather than ~/.lndk/data.
Perhaps we can add some checks to the CI to try to prevent this type of thing.
=> fix: data dir bugs

.github/workflows/release.yml, README.md, dist-workspace.toml, docs/cli_commands.md
This updates `dist` to 0.28.0.
And also fixes #189, and partially addresses #182 (does not advise on glibc linking minimums etc.)
=> Update dist & installation docs

.github/workflows/release.yml, dist-workspace.toml
addresses deprecation in actions/runner-images#11101
we might need to consider continue using cargo-dist after is unmaintained
=> chore: upgrade ubuntu image

Cargo.lock, Cargo.toml, tests/common/mod.rs, tests/integration_tests.rs
Follow @dunxen comment https://github.com/lndk-org/lndk/pull/206#pullrequestreview-2771557060.
This PR upgrades bitcoind, then remove the dependency in favor of corepc-node.
=> chore: use corepc-node instead of bitcoind

Cargo.lock, Cargo.toml
This PR is on top of #209 
In order to use latest bitcoind supported on corepc-node crate we need to update lnd.
This PR then upgrades lnd submodule to 0.18.5-beta and then upgrades itest to use bitcoind 28_0
=> chore: upgrade lnd submodule and bitcoind on itests

.github/workflows/main.yml, .gitignore, Cargo.lock, Cargo.toml, Makefile, README.md, flake.lock, flake.nix, nix/bitcoin.nix, nix/checks/flake-module.nix, nix/pkgs/flake-module.nix, nix/pkgs/rust.nix, nix/shells.nix, nix/treefmt.nix, tests/common/mod.rs, tests/integration_tests.rs
This PR adds a simple nix flake heavily inspired on [CLN](https://github.com/ElementsProject/lightning/pull/7656) one.
Few commands that now can be used
`nix develop` create a shell environment with all dependencies for development
`nix build`  or `nix build .#lndk` builds the projects to have executables `lndk and lndk-cli`
`nix flake check` checks formatting, tests and cargo audit. Does not check integration test.
Also add a check (without integrations) for nix on CI
=> chore: add simple nix flake

.github/workflows/main.yml
Fixes problems with toolchain on CI.
Stable was pointing to newer versions and then when building it did not find the components expected in our current version.
This handles that issue adding to `dtolnay/rust-toolchain` the specific version with the components.
@dunxen I added you as reviewer as it is short and you have been developing all CI related things 🙏🏼
=> chore: add components to rust build ci

Cargo.lock, Cargo.toml, src/lib.rs, src/lndk_offers.rs, src/onion_messenger.rs
This PR aims for 3 different changes.
1. We move `tonic_lnd` to our organization so it is easier to maintain.
2. `tonic_lnd` now is upgraded to protos `v0.18.5`, so we make use of them.
3. Thanks to tee8z [PR](https://github.com/lndk-org/tonic_lnd/pull/2) we support connecting to lnd instances that manage their own CA for their TLS certificates. For example, this would allow connecting to Voltage nodes.
1. Run integration tests
2. Local playground of paying offers
3. Connected to Voltage Node (it does not support onion messages yet, but still can connect)
=> chore: upgrades lnd protos v0.18.5

src/lib.rs, src/lnd.rs, src/lndk_offers.rs, src/main.rs
Based on [Matt's reply](https://github.com/lndk-org/lndk/issues/170#issuecomment-2886816019) on generating offers and receiving payments. This PR sits on top of #212 that already made changes on how we sign InvoiceRequests.
On 143edb505d9f6057837404346abd7e046bd1dff0 we change how ExpandedKey, key used on signatures and verifications, is generated. From a random-bytes to a deterministic way of doing it.
1. We define a static family key and index key
2. We sign a specific message: "LNDK:DO NOT SIGN THIS MANUALLY:SEED" Based on  [bLip 0050](https://github.com/lightning/blips/blob/master/blip-0050.md#link-lsps0ln_signature)
3. We hash the result of the signature and use it as a seed for the ExpandedKey
1. Do not generate expanded key out of randomness every startup
2. Remove some of unused …
=> ExpandedKey from lnd signature messages

src/offers/handler.rs, src/offers/lnd_requests.rs
This is a follow up on #216 fixing @f3r10 comments.
Mostly takes care of removing unneeded `Option`, fixes clippy redundant warnings and abstract away the `get_node_id` when it comes from a `scid`
=> Remove unused options and abstract `get_node_id`

proto/lndkrpc.proto, src/cli.rs, src/lnd.rs, src/offers/client_impls.rs, src/offers/handler.rs, src/offers/lnd_requests.rs, src/server.rs, tests/integration_tests.rs
Addresses issue #188 by enabling users to set custom fee limits when paying offers and invoices using the pay-offer and pay-invoice commands.
```bash
lndk-cli pay-offer lno1... --fee-limit 1000
lndk-cli pay-offer lno1... --fee-limit-percent 20
lndk-cli pay-invoice <hex> --fee-limit 1000
lndk-cli pay-invoice <hex> --fee-limit-percent 20
```
=> Add fees limits args in pay_invoice and pay_offer cli commands

Cargo.lock, Cargo.toml, proto/lndkrpc.proto, src/cli.rs, src/lib.rs, src/lnd.rs, src/main.rs, src/message_router.rs, src/offers/client_impls.rs, src/offers/handler.rs, src/offers/lnd_requests.rs, src/offers/mod.rs, src/server.rs, tests/common/mod.rs, tests/integration_tests.rs
This PR is on top of #216, and uses forked branch on top of v0.1.3 of rust lightning to expose already merged exposition of [`from_blinded_path_and_payinfo`](https://github.com/lightningdevkit/rust-lightning/pull/3807)  function.
This PR is _not ready_, sometimes `add_invoice` on LND's fails to build blinded paths and I left some _todos_ that I should tackle. I guess show early is better in these big features
**edit: this is fixed in 33b6fcb6452ac9b4dab8572c37316ba37ef8bc75**
Closes #170 (as mvp)
Handle exposes a function that given the constant `ExpandedKey` (from #214) creates an offer with a single path using `create_reply_path`. Probably we should add more than one.
Whenever a `RequestInvoice` message arrives, we check that context `Nonce` is present and we verify that the request. …
=> Create offer and receive payments

src/offers/handler.rs, tests/common/mod.rs, tests/integration_tests.rs
Whenever we send a payment we would take the first blinded path in the invoice, query the routes and finally send the payment. If something happens between getting the invoice and sending the payment it would fail.
This PR based on top of #216, goes through each blinded path to fulfill the invoice.
237102d96f195f33b2fbe943dac07fa6a7b67708 and 0a44ea12d7dafd6a21fdc1c699142e2e9261d88b are integration test improvements
83c4b1810a81348191ca701e5b8fda186cbbcb74 adds the retry mechanism with a simple integration test
=> Retry payments on failure

src/cli.rs, src/lnd.rs, src/offers/client_impls.rs, src/offers/lnd_requests.rs, src/offers/mod.rs, src/offers/parse.rs, src/server.rs
This PR is for https://github.com/lndk-org/lndk/issues/232. Standardize CLI error responses using machine codes from rpc details and Error enums.
---
- Use machine error codes from error enums in cli error respones
- Standardize CLI and grpc error messages.
- Refactor cli file. 
- There are still some nested Status (for eg. `PeerConnectError(LndStatus)`) that still shows json inner Lnd error Status, maybe we could just pack the LndStatus message.
`ERROR (PEER_CONNECT_ERROR): Failed to connect to peer: Status { code: NotFound, message: "unable to find node", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }`
- I am not sure if it is a problem to modify the error messages
**EDIT:**
I remove nested LndStatus from errors and simplify it to just add the …
=> Improve CLI error messages

dist-workspace.toml
fixes failed release on protobuf compiler issue.
=> chore: update protobuf version on ci release

README.md, docs/cli_commands.md
This commit updates README and docs folder that not updated on how can an offer be made and how LNDK now can use other data path for storing logs and TLS certs.
=> docs: add v0.3.0 specifics in documentation
